### ISSUE TITLE
Swerve Modules Turn Incorrectly

### ISSUE THREAD

**Issue by KenwoodFox** [FRC-1721/1721-RapidReact#1]
This issue was imported from here: https://github.com/FRC-1721/pre2022season/issues/9

**Comment by jeremyspin** [comment]
How do you fix a bug?

**Comment by KenwoodFox** [comment]
> How do you fix a bug?

Submit your code in a new PR that fixes the bug.

**Comment by KhanSimeoni** [comment]
Still needs optimization, but it works now
