### ISSUE TITLE
IMU Integration

### ISSUE THREAD

**Issue by KenwoodFox** [FRC-1721/1721-RapidReact#8]
The IMU is an integral part of odometry. See the lines here for implementation: https://github.com/FRC-1721/1721-RapidReact/blob/a39dae7754a623dc57e81198640ba0a6ab763a4c/rio/subsystems/drivetrain.py#L47-L51

You'll need to follow the ctre guides for the pidgeon https://docs.ctre-phoenix.com/en/stable/ch11_BringUpPigeon.html

**Comment by KenwoodFox** [comment]
![PXL_20220209_212731962.jpg](https://user-images.githubusercontent.com/31870999/153296539-3e97ec4e-403f-409f-a6f0-c028a752143e.jpg)

**Comment by jeremyspin** [comment]
What do we even do here specifically?

**Comment by KenwoodFox** [comment]
> What do we even do here specifically?

IMU needs to be integrated and tested.
